export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const AUTH_CHECK_COMPLETE = "AUTH_CHECK_COMPLETE";

export const REQUEST_EMAIL_LOGIN_OTP_REQUEST =
  "REQUEST_EMAIL_LOGIN_OTP_REQUEST";
export const REQUEST_EMAIL_LOGIN_OTP_SUCCESS =
  "REQUEST_EMAIL_LOGIN_OTP_SUCCESS";
export const REQUEST_EMAIL_LOGIN_OTP_FAILURE =
  "REQUEST_EMAIL_LOGIN_OTP_FAILURE";

export const VERIFY_EMAIL_LOGIN_OTP_REQUEST = "VERIFY_EMAIL_LOGIN_OTP_REQUEST";
export const VERIFY_EMAIL_LOGIN_OTP_SUCCESS = "VERIFY_EMAIL_LOGIN_OTP_SUCCESS";
export const VERIFY_EMAIL_LOGIN_OTP_FAILURE = "VERIFY_EMAIL_LOGIN_OTP_FAILURE";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

// Blog post actions
export const CREATE_BLOG_POST_REQUEST = "CREATE_BLOG_POST_REQUEST";
export const CREATE_BLOG_POST_SUCCESS = "CREATE_BLOG_POST_SUCCESS";
export const CREATE_BLOG_POST_FAILURE = "CREATE_BLOG_POST_FAILURE";

export const GET_ALL_BLOG_POSTS_REQUEST = "GET_ALL_BLOG_POSTS_REQUEST";
export const GET_ALL_BLOG_POSTS_SUCCESS = "GET_ALL_BLOG_POSTS_SUCCESS";
export const GET_ALL_BLOG_POSTS_FAILURE = "GET_ALL_BLOG_POSTS_FAILURE";

export const DELETE_BLOG_POST_REQUEST = "DELETE_BLOG_POST_REQUEST";
export const DELETE_BLOG_POST_SUCCESS = "DELETE_BLOG_POST_SUCCESS";
export const DELETE_BLOG_POST_FAILURE = "DELETE_BLOG_POST_FAILURE";

// Blog category actions

export const CREATE_BLOG_CATEGORY_REQUEST = "CREATE_BLOG_CATEGORY_REQUEST";
export const CREATE_BLOG_CATEGORY_SUCCESS = "CREATE_BLOG_CATEGORY_SUCCESS";
export const CREATE_BLOG_CATEGORY_FAILURE = "CREATE_BLOG_CATEGORY_FAILURE";

export const GET_BLOG_CATEGORY_REQUEST = "GET_BLOG_CATEGORY_REQUEST";
export const GET_BLOG_CATEGORY_SUCCESS = "GET_BLOG_CATEGORY_SUCCESS";
export const GET_BLOG_CATEGORY_FAILURE = "GET_BLOG_CATEGORY_FAILURE";

export const DELETE_BLOG_CATEGORY_REQUEST = "DELETE_BLOG_CATEGORY_REQUEST";
export const DELETE_BLOG_CATEGORY_SUCCESS = "DELETE_BLOG_CATEGORY_SUCCESS";
export const DELETE_BLOG_CATEGORY_FAILURE = "DELETE_BLOG_CATEGORY_FAILURE";

export const UPDATE_BLOG_STATUS_REQUEST = "UPDATE_BLOG_STATUS_REQUEST";
export const UPDATE_BLOG_STATUS_SUCCESS = "UPDATE_BLOG_STATUS_SUCCESS";
export const UPDATE_BLOG_STATUS_FAILURE = "UPDATE_BLOG_STATUS_FAILURE";

// Blog tag actions

export const CREATE_BLOG_TAG_REQUEST = "CREATE_BLOG_TAG_REQUEST";
export const CREATE_BLOG_TAG_SUCCESS = "CREATE_BLOG_TAG_SUCCESS";
export const CREATE_BLOG_TAG_FAILURE = "CREATE_BLOG_TAG_FAILURE";

export const GET_BLOG_TAG_REQUEST = "GET_BLOG_TAG_REQUEST";
export const GET_BLOG_TAG_SUCCESS = "GET_BLOG_TAG_SUCCESS";
export const GET_BLOG_TAG_FAILURE = "GET_BLOG_TAG_FAILURE";

export const DELETE_BLOG_TAG_REQUEST = "DELETE_BLOG_TAG_REQUEST";
export const DELETE_BLOG_TAG_SUCCESS = "DELETE_BLOG_TAG_SUCCESS";
export const DELETE_BLOG_TAG_FAILURE = "DELETE_BLOG_TAG_FAILURE";

// Lead actions
export const GET_LEAD_REQUEST = "GET_LEAD_REQUEST";
export const GET_LEAD_SUCCESS = "GET_LEAD_SUCCESS";
export const GET_LEAD_FAILURE = "GET_LEAD_FAILURE";

export const DELETE_LEAD_REQUEST = "DELETE_LEAD_REQUEST";
export const DELETE_LEAD_SUCCESS = "DELETE_LEAD_SUCCESS";
export const DELETE_LEAD_FAILURE = "DELETE_LEAD_FAILURE";

// Product actions
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

export const DUPLICATE_PRODUCT_REQUEST = "DUPLICATE_PRODUCT_REQUEST";
export const DUPLICATE_PRODUCT_SUCCESS = "DUPLICATE_PRODUCT_SUCCESS";
export const DUPLICATE_PRODUCT_FAILURE = "DUPLICATE_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const EXPORT_PRODUCTS_REQUEST = "EXPORT_PRODUCTS_REQUEST";
export const EXPORT_PRODUCTS_SUCCESS = "EXPORT_PRODUCTS_SUCCESS";
export const EXPORT_PRODUCTS_FAILURE = "EXPORT_PRODUCTS_FAILURE";

export const IMPORT_PRODUCTS_REQUEST = "IMPORT_PRODUCTS_REQUEST";
export const IMPORT_PRODUCTS_SUCCESS = "IMPORT_PRODUCTS_SUCCESS";
export const IMPORT_PRODUCTS_FAILURE = "IMPORT_PRODUCTS_FAILURE";

// Product Category actions
export const GET_PRODUCT_CATEGORIES_REQUEST = "GET_PRODUCT_CATEGORIES_REQUEST";
export const GET_PRODUCT_CATEGORIES_SUCCESS = "GET_PRODUCT_CATEGORIES_SUCCESS";
export const GET_PRODUCT_CATEGORIES_FAILURE = "GET_PRODUCT_CATEGORIES_FAILURE";

export const CREATE_PRODUCT_CATEGORY_REQUEST =
  "CREATE_PRODUCT_CATEGORY_REQUEST";
export const CREATE_PRODUCT_CATEGORY_SUCCESS =
  "CREATE_PRODUCT_CATEGORY_SUCCESS";
export const CREATE_PRODUCT_CATEGORY_FAILURE =
  "CREATE_PRODUCT_CATEGORY_FAILURE";

export const DELETE_PRODUCT_CATEGORY_REQUEST =
  "DELETE_PRODUCT_CATEGORY_REQUEST";
export const DELETE_PRODUCT_CATEGORY_SUCCESS =
  "DELETE_PRODUCT_CATEGORY_SUCCESS";
export const DELETE_PRODUCT_CATEGORY_FAILURE =
  "DELETE_PRODUCT_CATEGORY_FAILURE";

  // product tag actions
export const GET_PRODUCT_TAGS_REQUEST = "GET_PRODUCT_TAGS_REQUEST";
export const GET_PRODUCT_TAGS_SUCCESS = "GET_PRODUCT_TAGS_SUCCESS";
export const GET_PRODUCT_TAGS_FAILURE = "GET_PRODUCT_TAGS_FAILURE";

export const CREATE_PRODUCT_TAG_REQUEST = "CREATE_PRODUCT_TAG_REQUEST";
export const CREATE_PRODUCT_TAG_SUCCESS = "CREATE_PRODUCT_TAG_SUCCESS";
export const CREATE_PRODUCT_TAG_FAILURE = "CREATE_PRODUCT_TAG_FAILURE";

export const DELETE_PRODUCT_TAG_REQUEST = "DELETE_PRODUCT_TAG_REQUEST";
export const DELETE_PRODUCT_TAG_SUCCESS = "DELETE_PRODUCT_TAG_SUCCESS";
export const DELETE_PRODUCT_TAG_FAILURE = "DELETE_PRODUCT_TAG_FAILURE";

//Product Brand actions
export const GET_PRODUCT_BRANDS_REQUEST = "GET_PRODUCT_BRANDS_REQUEST";
export const GET_PRODUCT_BRANDS_SUCCESS = "GET_PRODUCT_BRANDS_SUCCESS";
export const GET_PRODUCT_BRANDS_FAILURE = "GET_PRODUCT_BRANDS_FAILURE";

export const CREATE_PRODUCT_BRAND_REQUEST = "CREATE_PRODUCT_BRAND_REQUEST";
export const CREATE_PRODUCT_BRAND_SUCCESS = "CREATE_PRODUCT_BRAND_SUCCESS";
export const CREATE_PRODUCT_BRAND_FAILURE = "CREATE_PRODUCT_BRAND_FAILURE";

export const DELETE_PRODUCT_BRAND_REQUEST = "DELETE_PRODUCT_BRAND_REQUEST";
export const DELETE_PRODUCT_BRAND_SUCCESS = "DELETE_PRODUCT_BRAND_SUCCESS";
export const DELETE_PRODUCT_BRAND_FAILURE = "DELETE_PRODUCT_BRAND_FAILURE";


// ========================
// REFERENCE ACTION TYPES
// ========================

export const GET_REFERENCE_DATA_REQUEST = "GET_REFERENCE_DATA_REQUEST";
export const GET_REFERENCE_DATA_SUCCESS = "GET_REFERENCE_DATA_SUCCESS";
export const GET_REFERENCE_DATA_FAILURE = "GET_REFERENCE_DATA_FAILURE";

export const ADD_REFERENCE_DATA_ITEM_REQUEST =
  "ADD_REFERENCE_DATA_ITEM_REQUEST";
export const ADD_REFERENCE_DATA_ITEM_SUCCESS =
  "ADD_REFERENCE_DATA_ITEM_SUCCESS";
export const ADD_REFERENCE_DATA_ITEM_FAILURE =
  "ADD_REFERENCE_DATA_ITEM_FAILURE";

export const REMOVE_REFERENCE_DATA_ITEM_REQUEST =
  "REMOVE_REFERENCE_DATA_ITEM_REQUEST";
export const REMOVE_REFERENCE_DATA_ITEM_SUCCESS =
  "REMOVE_REFERENCE_DATA_ITEM_SUCCESS";
export const REMOVE_REFERENCE_DATA_ITEM_FAILURE =
  "REMOVE_REFERENCE_DATA_ITEM_FAILURE";

export const UPDATE_REFERENCE_DATA_ITEM_REQUEST =
  "UPDATE_REFERENCE_DATA_ITEM_REQUEST";
export const UPDATE_REFERENCE_DATA_ITEM_SUCCESS =
  "UPDATE_REFERENCE_DATA_ITEM_SUCCESS";
export const UPDATE_REFERENCE_DATA_ITEM_FAILURE =
  "UPDATE_REFERENCE_DATA_ITEM_FAILURE";

export const GETWITHOUT_ADMIN_REFERENCE_DATA_REQUEST =
  "GETWITHOUT_ADMIN_REFERENCE_DATA_REQUEST";
export const GETWITHOUT_ADMIN_REFERENCE_DATA_SUCCESS =
  "GETWITHOUT_ADMIN_REFERENCE_DATA_SUCCESS";
export const GETWITHOUT_ADMIN_REFERENCE_DATA_FAILURE =
  "GETWITHOUT_ADMIN_REFERENCE_DATA_FAILURE";