export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const AUTH_CHECK_COMPLETE = "AUTH_CHECK_COMPLETE";

export const REQUEST_EMAIL_LOGIN_OTP_REQUEST =
  "REQUEST_EMAIL_LOGIN_OTP_REQUEST";
export const REQUEST_EMAIL_LOGIN_OTP_SUCCESS =
  "REQUEST_EMAIL_LOGIN_OTP_SUCCESS";
export const REQUEST_EMAIL_LOGIN_OTP_FAILURE =
  "REQUEST_EMAIL_LOGIN_OTP_FAILURE";

export const VERIFY_EMAIL_LOGIN_OTP_REQUEST = "VERIFY_EMAIL_LOGIN_OTP_REQUEST";
export const VERIFY_EMAIL_LOGIN_OTP_SUCCESS = "VERIFY_EMAIL_LOGIN_OTP_SUCCESS";
export const VERIFY_EMAIL_LOGIN_OTP_FAILURE = "VERIFY_EMAIL_LOGIN_OTP_FAILURE";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

// Blog post actions
export const CREATE_BLOG_POST_REQUEST = "CREATE_BLOG_POST_REQUEST";
export const CREATE_BLOG_POST_SUCCESS = "CREATE_BLOG_POST_SUCCESS";
export const CREATE_BLOG_POST_FAILURE = "CREATE_BLOG_POST_FAILURE";

export const GET_ALL_BLOG_POSTS_REQUEST = "GET_ALL_BLOG_POSTS_REQUEST";
export const GET_ALL_BLOG_POSTS_SUCCESS = "GET_ALL_BLOG_POSTS_SUCCESS";
export const GET_ALL_BLOG_POSTS_FAILURE = "GET_ALL_BLOG_POSTS_FAILURE";

export const DELETE_BLOG_POST_REQUEST = "DELETE_BLOG_POST_REQUEST";
export const DELETE_BLOG_POST_SUCCESS = "DELETE_BLOG_POST_SUCCESS";
export const DELETE_BLOG_POST_FAILURE = "DELETE_BLOG_POST_FAILURE";

// Blog category actions

export const CREATE_BLOG_CATEGORY_REQUEST = "CREATE_BLOG_CATEGORY_REQUEST";
export const CREATE_BLOG_CATEGORY_SUCCESS = "CREATE_BLOG_CATEGORY_SUCCESS";
export const CREATE_BLOG_CATEGORY_FAILURE = "CREATE_BLOG_CATEGORY_FAILURE";

export const GET_BLOG_CATEGORY_REQUEST = "GET_BLOG_CATEGORY_REQUEST";
export const GET_BLOG_CATEGORY_SUCCESS = "GET_BLOG_CATEGORY_SUCCESS";
export const GET_BLOG_CATEGORY_FAILURE = "GET_BLOG_CATEGORY_FAILURE";

export const DELETE_BLOG_CATEGORY_REQUEST = "DELETE_BLOG_CATEGORY_REQUEST";
export const DELETE_BLOG_CATEGORY_SUCCESS = "DELETE_BLOG_CATEGORY_SUCCESS";
export const DELETE_BLOG_CATEGORY_FAILURE = "DELETE_BLOG_CATEGORY_FAILURE";

export const UPDATE_BLOG_STATUS_REQUEST = "UPDATE_BLOG_STATUS_REQUEST";
export const UPDATE_BLOG_STATUS_SUCCESS = "UPDATE_BLOG_STATUS_SUCCESS";
export const UPDATE_BLOG_STATUS_FAILURE = "UPDATE_BLOG_STATUS_FAILURE";

// Blog tag actions

export const CREATE_BLOG_TAG_REQUEST = "CREATE_BLOG_TAG_REQUEST";
export const CREATE_BLOG_TAG_SUCCESS = "CREATE_BLOG_TAG_SUCCESS";
export const CREATE_BLOG_TAG_FAILURE = "CREATE_BLOG_TAG_FAILURE";

export const GET_BLOG_TAG_REQUEST = "GET_BLOG_TAG_REQUEST";
export const GET_BLOG_TAG_SUCCESS = "GET_BLOG_TAG_SUCCESS";
export const GET_BLOG_TAG_FAILURE = "GET_BLOG_TAG_FAILURE";

export const DELETE_BLOG_TAG_REQUEST = "DELETE_BLOG_TAG_REQUEST";
export const DELETE_BLOG_TAG_SUCCESS = "DELETE_BLOG_TAG_SUCCESS";
export const DELETE_BLOG_TAG_FAILURE = "DELETE_BLOG_TAG_FAILURE";

// Lead actions
export const GET_LEAD_REQUEST = "GET_LEAD_REQUEST";
export const GET_LEAD_SUCCESS = "GET_LEAD_SUCCESS";
export const GET_LEAD_FAILURE = "GET_LEAD_FAILURE";

export const DELETE_LEAD_REQUEST = "DELETE_LEAD_REQUEST";
export const DELETE_LEAD_SUCCESS = "DELETE_LEAD_SUCCESS";
export const DELETE_LEAD_FAILURE = "DELETE_LEAD_FAILURE";