export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const AUTH_CHECK_COMPLETE = "AUTH_CHECK_COMPLETE";

export const REQUEST_EMAIL_LOGIN_OTP_REQUEST =
  "REQUEST_EMAIL_LOGIN_OTP_REQUEST";
export const REQUEST_EMAIL_LOGIN_OTP_SUCCESS =
  "REQUEST_EMAIL_LOGIN_OTP_SUCCESS";
export const REQUEST_EMAIL_LOGIN_OTP_FAILURE =
  "REQUEST_EMAIL_LOGIN_OTP_FAILURE";

export const VERIFY_EMAIL_LOGIN_OTP_REQUEST = "VERIFY_EMAIL_LOGIN_OTP_REQUEST";
export const VERIFY_EMAIL_LOGIN_OTP_SUCCESS = "VERIFY_EMAIL_LOGIN_OTP_SUCCESS";
export const VERIFY_EMAIL_LOGIN_OTP_FAILURE = "VERIFY_EMAIL_LOGIN_OTP_FAILURE";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

// Blog post actions
export const CREATE_BLOG_POST_REQUEST = "CREATE_BLOG_POST_REQUEST";
export const CREATE_BLOG_POST_SUCCESS = "CREATE_BLOG_POST_SUCCESS";
export const CREATE_BLOG_POST_FAILURE = "CREATE_BLOG_POST_FAILURE";

export const GET_ALL_BLOG_POSTS_REQUEST = "GET_ALL_BLOG_POSTS_REQUEST";
export const GET_ALL_BLOG_POSTS_SUCCESS = "GET_ALL_BLOG_POSTS_SUCCESS";
export const GET_ALL_BLOG_POSTS_FAILURE = "GET_ALL_BLOG_POSTS_FAILURE";

export const DELETE_BLOG_POST_REQUEST = "DELETE_BLOG_POST_REQUEST";
export const DELETE_BLOG_POST_SUCCESS = "DELETE_BLOG_POST_SUCCESS";
export const DELETE_BLOG_POST_FAILURE = "DELETE_BLOG_POST_FAILURE";

// Blog category actions

export const CREATE_BLOG_CATEGORY_REQUEST = "CREATE_BLOG_CATEGORY_REQUEST";
export const CREATE_BLOG_CATEGORY_SUCCESS = "CREATE_BLOG_CATEGORY_SUCCESS";
export const CREATE_BLOG_CATEGORY_FAILURE = "CREATE_BLOG_CATEGORY_FAILURE";

export const GET_BLOG_CATEGORY_REQUEST = "GET_BLOG_CATEGORY_REQUEST";
export const GET_BLOG_CATEGORY_SUCCESS = "GET_BLOG_CATEGORY_SUCCESS";
export const GET_BLOG_CATEGORY_FAILURE = "GET_BLOG_CATEGORY_FAILURE";

export const DELETE_BLOG_CATEGORY_REQUEST = "DELETE_BLOG_CATEGORY_REQUEST";
export const DELETE_BLOG_CATEGORY_SUCCESS = "DELETE_BLOG_CATEGORY_SUCCESS";
export const DELETE_BLOG_CATEGORY_FAILURE = "DELETE_BLOG_CATEGORY_FAILURE";

export const UPDATE_BLOG_STATUS_REQUEST = "UPDATE_BLOG_STATUS_REQUEST";
export const UPDATE_BLOG_STATUS_SUCCESS = "UPDATE_BLOG_STATUS_SUCCESS";
export const UPDATE_BLOG_STATUS_FAILURE = "UPDATE_BLOG_STATUS_FAILURE";

// Blog tag actions

export const CREATE_BLOG_TAG_REQUEST = "CREATE_BLOG_TAG_REQUEST";
export const CREATE_BLOG_TAG_SUCCESS = "CREATE_BLOG_TAG_SUCCESS";
export const CREATE_BLOG_TAG_FAILURE = "CREATE_BLOG_TAG_FAILURE";

export const GET_BLOG_TAG_REQUEST = "GET_BLOG_TAG_REQUEST";
export const GET_BLOG_TAG_SUCCESS = "GET_BLOG_TAG_SUCCESS";
export const GET_BLOG_TAG_FAILURE = "GET_BLOG_TAG_FAILURE";

export const DELETE_BLOG_TAG_REQUEST = "DELETE_BLOG_TAG_REQUEST";
export const DELETE_BLOG_TAG_SUCCESS = "DELETE_BLOG_TAG_SUCCESS";
export const DELETE_BLOG_TAG_FAILURE = "DELETE_BLOG_TAG_FAILURE";

// Lead actions
export const GET_LEAD_REQUEST = "GET_LEAD_REQUEST";
export const GET_LEAD_SUCCESS = "GET_LEAD_SUCCESS";
export const GET_LEAD_FAILURE = "GET_LEAD_FAILURE";

export const DELETE_LEAD_REQUEST = "DELETE_LEAD_REQUEST";
export const DELETE_LEAD_SUCCESS = "DELETE_LEAD_SUCCESS";
export const DELETE_LEAD_FAILURE = "DELETE_LEAD_FAILURE";

// Product actions
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

export const DUPLICATE_PRODUCT_REQUEST = "DUPLICATE_PRODUCT_REQUEST";
export const DUPLICATE_PRODUCT_SUCCESS = "DUPLICATE_PRODUCT_SUCCESS";
export const DUPLICATE_PRODUCT_FAILURE = "DUPLICATE_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const EXPORT_PRODUCTS_REQUEST = "EXPORT_PRODUCTS_REQUEST";
export const EXPORT_PRODUCTS_SUCCESS = "EXPORT_PRODUCTS_SUCCESS";
export const EXPORT_PRODUCTS_FAILURE = "EXPORT_PRODUCTS_FAILURE";

export const IMPORT_PRODUCTS_REQUEST = "IMPORT_PRODUCTS_REQUEST";
export const IMPORT_PRODUCTS_SUCCESS = "IMPORT_PRODUCTS_SUCCESS";
export const IMPORT_PRODUCTS_FAILURE = "IMPORT_PRODUCTS_FAILURE";

// Product Category actions
export const GET_PRODUCT_CATEGORIES_REQUEST = "GET_PRODUCT_CATEGORIES_REQUEST";
export const GET_PRODUCT_CATEGORIES_SUCCESS = "GET_PRODUCT_CATEGORIES_SUCCESS";
export const GET_PRODUCT_CATEGORIES_FAILURE = "GET_PRODUCT_CATEGORIES_FAILURE";

export const CREATE_PRODUCT_CATEGORY_REQUEST =
  "CREATE_PRODUCT_CATEGORY_REQUEST";
export const CREATE_PRODUCT_CATEGORY_SUCCESS =
  "CREATE_PRODUCT_CATEGORY_SUCCESS";
export const CREATE_PRODUCT_CATEGORY_FAILURE =
  "CREATE_PRODUCT_CATEGORY_FAILURE";

export const DELETE_PRODUCT_CATEGORY_REQUEST =
  "DELETE_PRODUCT_CATEGORY_REQUEST";
export const DELETE_PRODUCT_CATEGORY_SUCCESS =
  "DELETE_PRODUCT_CATEGORY_SUCCESS";
export const DELETE_PRODUCT_CATEGORY_FAILURE =
  "DELETE_PRODUCT_CATEGORY_FAILURE";

// product tag actions
export const GET_PRODUCT_TAGS_REQUEST = "GET_PRODUCT_TAGS_REQUEST";
export const GET_PRODUCT_TAGS_SUCCESS = "GET_PRODUCT_TAGS_SUCCESS";
export const GET_PRODUCT_TAGS_FAILURE = "GET_PRODUCT_TAGS_FAILURE";

export const CREATE_PRODUCT_TAG_REQUEST = "CREATE_PRODUCT_TAG_REQUEST";
export const CREATE_PRODUCT_TAG_SUCCESS = "CREATE_PRODUCT_TAG_SUCCESS";
export const CREATE_PRODUCT_TAG_FAILURE = "CREATE_PRODUCT_TAG_FAILURE";

export const DELETE_PRODUCT_TAG_REQUEST = "DELETE_PRODUCT_TAG_REQUEST";
export const DELETE_PRODUCT_TAG_SUCCESS = "DELETE_PRODUCT_TAG_SUCCESS";
export const DELETE_PRODUCT_TAG_FAILURE = "DELETE_PRODUCT_TAG_FAILURE";

//Product Brand actions
export const GET_PRODUCT_BRANDS_REQUEST = "GET_PRODUCT_BRANDS_REQUEST";
export const GET_PRODUCT_BRANDS_SUCCESS = "GET_PRODUCT_BRANDS_SUCCESS";
export const GET_PRODUCT_BRANDS_FAILURE = "GET_PRODUCT_BRANDS_FAILURE";

export const CREATE_PRODUCT_BRAND_REQUEST = "CREATE_PRODUCT_BRAND_REQUEST";
export const CREATE_PRODUCT_BRAND_SUCCESS = "CREATE_PRODUCT_BRAND_SUCCESS";
export const CREATE_PRODUCT_BRAND_FAILURE = "CREATE_PRODUCT_BRAND_FAILURE";

export const DELETE_PRODUCT_BRAND_REQUEST = "DELETE_PRODUCT_BRAND_REQUEST";
export const DELETE_PRODUCT_BRAND_SUCCESS = "DELETE_PRODUCT_BRAND_SUCCESS";
export const DELETE_PRODUCT_BRAND_FAILURE = "DELETE_PRODUCT_BRAND_FAILURE";


// ========================
// REFERENCE ACTION TYPES
// ========================

export const GET_REFERENCE_DATA_REQUEST = "GET_REFERENCE_DATA_REQUEST";
export const GET_REFERENCE_DATA_SUCCESS = "GET_REFERENCE_DATA_SUCCESS";
export const GET_REFERENCE_DATA_FAILURE = "GET_REFERENCE_DATA_FAILURE";

export const ADD_REFERENCE_DATA_ITEM_REQUEST =
  "ADD_REFERENCE_DATA_ITEM_REQUEST";
export const ADD_REFERENCE_DATA_ITEM_SUCCESS =
  "ADD_REFERENCE_DATA_ITEM_SUCCESS";
export const ADD_REFERENCE_DATA_ITEM_FAILURE =
  "ADD_REFERENCE_DATA_ITEM_FAILURE";

export const REMOVE_REFERENCE_DATA_ITEM_REQUEST =
  "REMOVE_REFERENCE_DATA_ITEM_REQUEST";
export const REMOVE_REFERENCE_DATA_ITEM_SUCCESS =
  "REMOVE_REFERENCE_DATA_ITEM_SUCCESS";
export const REMOVE_REFERENCE_DATA_ITEM_FAILURE =
  "REMOVE_REFERENCE_DATA_ITEM_FAILURE";

export const UPDATE_REFERENCE_DATA_ITEM_REQUEST =
  "UPDATE_REFERENCE_DATA_ITEM_REQUEST";
export const UPDATE_REFERENCE_DATA_ITEM_SUCCESS =
  "UPDATE_REFERENCE_DATA_ITEM_SUCCESS";
export const UPDATE_REFERENCE_DATA_ITEM_FAILURE =
  "UPDATE_REFERENCE_DATA_ITEM_FAILURE";

// ========================
// PROJECTS ACTION TYPES
// ========================

export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";

export const GET_PROJECT_BY_ID_REQUEST = "GET_PROJECT_BY_ID_REQUEST";
export const GET_PROJECT_BY_ID_SUCCESS = "GET_PROJECT_BY_ID_SUCCESS";
export const GET_PROJECT_BY_ID_FAILURE = "GET_PROJECT_BY_ID_FAILURE";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

export const TOGGLE_PROJECT_STATUS_REQUEST = "TOGGLE_PROJECT_STATUS_REQUEST";
export const TOGGLE_PROJECT_STATUS_SUCCESS = "TOGGLE_PROJECT_STATUS_SUCCESS";
export const TOGGLE_PROJECT_STATUS_FAILURE = "TOGGLE_PROJECT_STATUS_FAILURE";

export const GET_VISITORS_BY_PROJECT_ID_REQUEST =
  "GET_VISITORS_BY_PROJECT_ID_REQUEST";
export const GET_VISITORS_BY_PROJECT_ID_SUCCESS =
  "GET_VISITORS_BY_PROJECT_ID_SUCCESS";
export const GET_VISITORS_BY_PROJECT_ID_FAILURE =
  "GET_VISITORS_BY_PROJECT_ID_FAILURE";

export const GET_BROKER_BY_PROJECT_ID_REQUEST =
  "GET_BROKER_BY_PROJECT_ID_REQUEST";
export const GET_BROKER_BY_PROJECT_ID_SUCCESS =
  "GET_BROKER_BY_PROJECT_ID_SUCCESS";
export const GET_BROKER_BY_PROJECT_ID_FAILURE =
  "GET_BROKER_BY_PROJECT_ID_FAILURE";

export const EXPORT_PROJECT_DATA_REQUEST = "EXPORT_PROJECT_DATA_REQUEST";
export const EXPORT_PROJECT_DATA_SUCCESS = "EXPORT_PROJECT_DATA_SUCCESS";
export const EXPORT_PROJECT_DATA_FAILURE = "EXPORT_PROJECT_DATA_FAILURE";

export const DELETE_PROJECT_MEDIA_REQUEST = "DELETE_PROJECT_MEDIA_REQUEST";
export const DELETE_PROJECT_MEDIA_SUCCESS = "DELETE_PROJECT_MEDIA_SUCCESS";
export const DELETE_PROJECT_MEDIA_FAILURE = "DELETE_PROJECT_MEDIA_FAILURE";

// ========================
// BROKERS ACTION TYPES
// ========================

export const GET_BROKERS_REQUEST = "GET_BROKERS_REQUEST";
export const GET_BROKERS_SUCCESS = "GET_BROKERS_SUCCESS";
export const GET_BROKERS_FAILURE = "GET_BROKERS_FAILURE";

export const CREATE_BROKER_REQUEST = "CREATE_BROKER_REQUEST";
export const CREATE_BROKER_SUCCESS = "CREATE_BROKER_SUCCESS";
export const CREATE_BROKER_FAILURE = "CREATE_BROKER_FAILURE";

export const GET_BROKER_BY_ID_REQUEST = "GET_BROKER_BY_ID_REQUEST";
export const GET_BROKER_BY_ID_SUCCESS = "GET_BROKER_BY_ID_SUCCESS";
export const GET_BROKER_BY_ID_FAILURE = "GET_BROKER_BY_ID_FAILURE";

export const UPDATE_BROKER_REQUEST = "UPDATE_BROKER_REQUEST";
export const UPDATE_BROKER_SUCCESS = "UPDATE_BROKER_SUCCESS";
export const UPDATE_BROKER_FAILURE = "UPDATE_BROKER_FAILURE";

export const APPROVE_BROKER_REQUEST = "APPROVE_BROKER_REQUEST";
export const APPROVE_BROKER_SUCCESS = "APPROVE_BROKER_SUCCESS";
export const APPROVE_BROKER_FAILURE = "APPROVE_BROKER_FAILURE";

export const REJECT_BROKER_REQUEST = "REJECT_BROKER_REQUEST";
export const REJECT_BROKER_SUCCESS = "REJECT_BROKER_SUCCESS";
export const REJECT_BROKER_FAILURE = "REJECT_BROKER_FAILURE";

export const EXPORT_BROKER_DATA_REQUEST = "EXPORT_BROKER_DATA_REQUEST";
export const EXPORT_BROKER_DATA_SUCCESS = "EXPORT_BROKER_DATA_SUCCESS";
export const EXPORT_BROKER_DATA_FAILURE = "EXPORT_BROKER_DATA_FAILURE";

export const DELETE_BROKER_REQUEST = "DELETE_BROKER_REQUEST";
export const DELETE_BROKER_SUCCESS = "DELETE_BROKER_SUCCESS";
export const DELETE_BROKER_FAILURE = "DELETE_BROKER_FAILURE";

export const REFERED_VISITORS_BY_BROKER_REQUEST =
  "REFERED_VISITORS_BY_BROKER_REQUEST";
export const REFERED_VISITORS_BY_BROKER_SUCCESS =
  "REFERED_VISITORS_BY_BROKER_SUCCESS";
export const REFERED_VISITORS_BY_BROKER_FAILURE =
  "REFERED_VISITORS_BY_BROKER_FAILURE";

// ========================
// BROKER KPI ACTION TYPES
// ========================

export const GET_BROKER_KPI_REQUEST = "GET_BROKER_KPI_REQUEST";
export const GET_BROKER_KPI_SUCCESS = "GET_BROKER_KPI_SUCCESS";
export const GET_BROKER_KPI_FAILURE = "GET_BROKER_KPI_FAILURE"

// ========================
// BROKER TEAM ACTION TYPES
// ========================

export const GET_BROKER_TEAM_REQUEST = "GET_BROKER_TEAM_REQUEST";
export const GET_BROKER_TEAM_SUCCESS = "GET_BROKER_TEAM_SUCCESS";
export const GET_BROKER_TEAM_FAILURE = "GET_BROKER_TEAM_FAILURE";

export const UPDATE_BROKER_TEAM_MEMBER_STATUS_REQUEST =
  "UPDATE_BROKER_TEAM_MEMBER_STATUS_REQUEST";
export const UPDATE_BROKER_TEAM_MEMBER_STATUS_SUCCESS =
  "UPDATE_BROKER_TEAM_MEMBER_STATUS_SUCCESS";
export const UPDATE_BROKER_TEAM_MEMBER_STATUS_FAILURE =
  "UPDATE_BROKER_TEAM_MEMBER_STATUS_FAILURE";

// ========================
//SALE RM
// ========================

export const GET_SALES_RM_REQUEST = "GET_SALES_RM_REQUEST";
export const GET_SALES_RM_SUCCESS = "GET_SALES_RM_SUCCESS";
export const GET_SALES_RM_FAILURE = "GET_SALES_RM_FAILURE";

// ========================
// VISITOR ACTION TYPES
// ========================

export const FETCH_VISITORS_REQUEST = "FETCH_VISITORS_REQUEST";
export const FETCH_VISITORS_SUCCESS = "FETCH_VISITORS_SUCCESS";
export const FETCH_VISITORS_FAILURE = "FETCH_VISITORS_FAILURE";

export const FETCH_VISITOR_BY_ID_REQUEST = "FETCH_VISITOR_BY_ID_REQUEST";
export const FETCH_VISITOR_BY_ID_SUCCESS = "FETCH_VISITOR_BY_ID_SUCCESS";
export const FETCH_VISITOR_BY_ID_FAILURE = "FETCH_VISITOR_BY_ID_FAILURE";

export const UPDATE_VISITOR_REQUEST = "UPDATE_VISITOR_REQUEST";
export const UPDATE_VISITOR_SUCCESS = "UPDATE_VISITOR_SUCCESS";
export const UPDATE_VISITOR_FAILURE = "UPDATE_VISITOR_FAILURE";

export const FETCH_VISITOR_HISTORY_REQUEST = "FETCH_VISITOR_HISTORY_REQUEST";
export const FETCH_VISITOR_HISTORY_SUCCESS = "FETCH_VISITOR_HISTORY_SUCCESS";
export const FETCH_VISITOR_HISTORY_FAILURE = "FETCH_VISITOR_HISTORY_FAILURE";

export const EXPORT_VISITOR_DATA_REQUEST = "EXPORT_VISITOR_DATA_REQUEST";
export const EXPORT_VISITOR_DATA_SUCCESS = "EXPORT_VISITOR_DATA_SUCCESS";
export const EXPORT_VISITOR_DATA_FAILURE = "EXPORT_VISITOR_DATA_FAILURE";

export const VISITOR_TAG_HISTORY_REQUEST = "VISITOR_TAG_HISTORY_REQUEST";
export const VISITOR_TAG_HISTORY_SUCCESS = "VISITOR_TAG_HISTORY_SUCCESS";
export const VISITOR_TAG_HISTORY_FAILURE = "VISITOR_TAG_HISTORY_FAILURE";

// ========================
// VISITS ACTION TYPES
// ========================

export const FETCH_VISITS_REQUEST = "FETCH_VISITS_REQUEST";
export const FETCH_VISITS_SUCCESS = "FETCH_VISITS_SUCCESS";
export const FETCH_VISITS_FAILURE = "FETCH_VISITS_FAILURE";

export const FETCH_VISIT_BY_ID_REQUEST = "FETCH_VISIT_BY_ID_REQUEST";
export const FETCH_VISIT_BY_ID_SUCCESS = "FETCH_VISIT_BY_ID_SUCCESS";
export const FETCH_VISIT_BY_ID_FAILURE = "FETCH_VISIT_BY_ID_FAILURE";

export const FETCH_VISIT_HISTORY_REQUEST = "FETCH_VISIT_HISTORY_REQUEST";
export const FETCH_VISIT_HISTORY_SUCCESS = "FETCH_VISIT_HISTORY_SUCCESS";
export const FETCH_VISIT_HISTORY_FAILURE = "FETCH_VISIT_HISTORY_FAILURE";