export const BASE_URL = "http://localhost:5000";
export const IMAGE_BASE_URL = "http://localhost:5000/uploads/";

export const API_ENDPOINTS = {
  REGISTER: "/api/auth/register",
  LOGIN: "/api/auth/login",
  SEND_OTP: "/api/auth/send-otp",
  VERIFY_OTP: "/api/auth/verify-otp",
  RESET_PASSWORD: "/api/auth/reset-password",
  GET_USER_PROFILE: "/api/auth/profile",
  GET_ALL_USERS: "/api/auth/all-users",
  
  CREATE_BLOG_POST: "/api/blog/posts",
  GET_ALL_BLOG_POSTS: "/api/blog/posts",
  DELETE_BLOG_POST: "/api/blog/posts/",
  CREATE_BLOG_CATEGORY: "/api/blog/categories",
  GET_BLOG_CATEGORY: "/api/blog/categories",
  DELETE_BLOG_CATEGORY: "/api/blog/categories/",
  CREATE_BLOG_TAG: "/api/blog/tags",
  GET_BLOG_TAG: "/api/blog/tags",
  DELETE_BLOG_TAG: "/api/blog/tags/",
  UPDATE_BLOG_STATUS: "/api/blog/posts/",
  GET_LEAD: "/api/contact/all",
  DELETE_LEAD: "/api/contact/",
  GET_PRODUCTS: "/api/products",
  GET_PRODUCT_BY_ID: "/api/products/",
  CREATE_PRODUCT: "/api/products",
  DUPLICATE_PRODUCT: "/api/products",
  DELETE_PRODUCT: "/api/products/",
  UPDATE_PRODUCT: "/api/products/",
  EXPORT_PRODUCTS: "/api/products/export/all",
  IMPORT_PRODUCTS: "/api/products/import/csv",
  GET_PRODUCT_CATEGORIES: "/api/product-categories",
  CREATE_PRODUCT_CATEGORY: "/api/product-categories",
  DELETE_PRODUCT_CATEGORY: "/api/product-categories/",
  GET_PRODUCT_TAGS: "/api/product-tags",
  CREATE_PRODUCT_TAG: "/api/product-tags",
  DELETE_PRODUCT_TAG: "/api/product-tags/",
  GET_PRODUCT_BRANDS: "/api/product-brands",
  CREATE_PRODUCT_BRAND: "/api/product-brands",
  DELETE_PRODUCT_BRAND: "/api/product-brands/",

  REFERENCE_DATA: "/api/reference",
  ADD_REFERENCE_DATA_ITEM: "/api/reference",
  UPDATE_REFERENCE_DATA_ITEM: "/api/reference/",
  REMOVE_REFERENCE_DATA_ITEM: "/api/reference/item/",

  PROJECTS: "/api/projects",
  GET_PROJECT_BY_ID: "/api/projects/",
  CREATE_PROJECT: "/api/projects",
  UPDATE_PROJECT: "/api/projects/",
  DELETE_PROJECT: "/api/projects/",
  TOGGLE_PROJECT_STATUS: "/api/projects/toggle-status/",
  EXPORT_PROJECT_DATA: "/api/projects/export/",
  // VISITORBYPROJECT: "/api/projects/visitors/",
  // BROKERBYPROJECT: "/api/projects/brokers/",

  BROKERS: "/api/brokers/",
  GET_BROKER_BY_ID: "/api/brokers/",
  CREATE_BROKER: "/api/brokers",
  UPDATE_BROKER: "/api/brokers/",
  DELETE_BROKER: "/api/brokers/",
  TOGGLE_BROKER_STATUS: "/api/brokers/toggle-status/",
  EXPORT_BROKER_DATA: "/api/brokers/export/",
  BROKER_TEAM: "/api/brokers/team/",

  VISITORS: "/api/visitors/",
  VISITOR_TAG_HISTORY: "/api/visits/visitors/",
  VISITOR_HISTORY: "/api/visits/visitor-history/",
  EXPORT_VISITOR_DATA: "/api/visitors/export/",
};
